

version = 0.1

[default.deploy.parameters]
stack_name = "bp-node-test-yes"
resolve_s3 = false
s3_prefix = "binay-node-test-yes"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
s3_bucket = "binay-node"